name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version'
        required: true
      prerelease:
        description: 'Pre-release'
        required: false
        type: boolean
      patch:
        description: 'Remote Patch'
        required: false
      ref:
        description: 'Branch, Tag or SHA'
        required: false

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
      - name: Apply patch
        run: |
          git submodule update --init --remote
          cd FFmpegFreeUI
          if [ -n "${{ inputs.ref }}" ]; then
            git checkout "${{ inputs.ref }}"
          fi
          if [ -n "${{ inputs.patch }}" ]; then
            curl -LsSf "${{ inputs.patch }}" | git apply
          fi
          git apply ../patches/*.patch
      - name: Build and Publish - NoSelfContained SingleFile
        working-directory: ./FFmpegFreeUI
        run: |
          dotnet publish FFmpegFreeUI/FFmpegFreeUI.vbproj \
            -c Release \
            -r win-${{ matrix.arch }} \
            --no-self-contained \
            -p:DebugType=none \
            -p:PublishSingleFile=true \
            -p:PublishReadyToRun=false \
            -p:PublishReadyToRunEmitSymbols=false \
            -p:EnableCompressionInSingleFile=false \
            -o ./publish/NoSelfContained-SingleFile-${{ matrix.arch }}
      - name: Create 7z archives
        run: |
          7z a FFmpegFreeUI-NoSelfContained-SingleFile-win-${{ matrix.arch }}.7z ./FFmpegFreeUI/publish/NoSelfContained-SingleFile-${{ matrix.arch }}/*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: FFmpegFreeUI-*-win-${{ matrix.arch }}.7z
          prerelease: ${{ inputs.prerelease }}
          tag_name: ${{ inputs.tag }}
